# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/SamHatami"

[social.params]
icon = "brand-github"

[[social]]
name = "LinkedIn"
url = "www.linkedin.com/in/sammostache"

[social.params]
icon = "linkedin-svgrepo-com"
